### ISSUE TITLE
Crash upon selecting damage log when opening program from file explorer

### ISSUE THREAD

**Issue by GHNeko** [AterialDawn/ApexParse#5]
Application "ApexParse" unhandled exception
Timestamp : Sunday, 28 July, 2019 18:20:34

Exception object dump : 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApexParse.ViewModel.MainWindowViewModel.initializeDamageParser(String logPath) in C:\Users\AterialDawn\Documents\Visual Studio 2015\Projects\ApexParse\ApexParse\ViewModel\MainWindowViewModel.cs:line 530
   at ApexParse.ViewModel.MainWindowViewModel.selectDamageLogsPath() in C:\Users\AterialDawn\Documents\Visual Studio 2015\Projects\ApexParse\ApexParse\ViewModel\MainWindowViewModel.cs:line 519
   at ApexParse.ViewModel.MainWindowViewModel..ctor() in C:\Users\AterialDawn\Documents\Visual Studio 2015\Projects\ApexParse\ApexParse\ViewModel\MainWindowViewModel.cs:line 206
   at ApexParse.App.OnStartup(StartupEventArgs e) in C:\Users\AterialDawn\Documents\Visual Studio 2015\Projects\ApexParse\ApexParse\App.xaml.cs:line 38
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AterialDawn** [comment]
The quickest fix in the west. If anyone else is still getting this, redownload the release
